#!C:/Users/Deldor/AppData/Local/Programs/Python/Python38-32/python.exe

import re
import sys


commit_pattern = r'^\[[0-9]+\][a-z]+'
msg = ''
with open(sys.argv[1], 'r') as os:
    msg = os.read()


if not re.match(commit_pattern, msg):
    print('Incorrect commit')
    sys.exit(-1)